Improve HttpEventAdaptor logs
wso2/carbon-analytics-common pull request #798
Opened 2022-07-07 04:29 UTC by ChanikaRuchini

## Purpose
In the current implementation of the adapter, response codes are not handled and due to that runtime errors while can not be troubleshooted. Hence we need to improve the current adapter to log detailed errors for troubleshooting purposes .

2022-07-07 05:02 UTC, wenodpathirana commented on components/event-publisher/event-output-adapters/org.wso2.carbon.event.output.adapter.http/src/main/java/org/wso2/carbon/event/output/adapter/http/HTTPEventAdapter.java
> +                    log.error("Error while connecting the endpoint. Relieved HTTP response code is : " +
better if we can log the error details in the reponse, you can access them from `method` object.

2022-07-07 11:28 UTC, wenodpathirana approved these changes

2022-07-07 11:41 UTC, ChanikaRuchini commented on components/event-publisher/event-output-adapters/org.wso2.carbon.event.output.adapter.http/src/main/java/org/wso2/carbon/event/output/adapter/http/HTTPEventAdapterFactory.java
> +        return false;
fixed

2022-07-08 01:33 UTC, AnuGayan requested changes

2022-07-08 01:33 UTC, AnuGayan commented on components/event-publisher/event-output-adapters/org.wso2.carbon.event.output.adapter.http/src/main/java/org/wso2/carbon/event/output/adapter/http/HTTPEventAdapter.java
> +                        log.info("Successfully connected to the endpoint. Received HTTP response code is : " +
Shall we make this debug?

2022-07-08 04:10 UTC, ChanikaRuchini commented on components/event-publisher/event-output-adapters/org.wso2.carbon.event.output.adapter.http/src/main/java/org/wso2/carbon/event/output/adapter/http/HTTPEventAdapter.java
> +                        log.info("Successfully connected to the endpoint. Received HTTP response code is : " +
Fixed

2022-07-08 04:22 UTC, AnuGayan approved these changes

2022-07-08 04:22 UTC, merged